name: Deploy to Staging server

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js

        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc -i --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: ec2-13-40-119-155.eu-west-2.compute.amazonaws.com
          REMOTE_USER: ec2-user
          TARGET: /home/ec2-user/Coursework-Intro-to-Cloud-Week-1
          EXCLUDE: '/dist/, /node_modules/'
