name: Deploy to Staging server

on:
  workflow_run:
    workflows:
      - 'Lint on push'
      - 'Run unit tests on push / pull'
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-13-40-119-155.eu-west-2.compute.amazonaws.com
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin main
            exit
            EOF
