name: Deploy to Staging server

on:
  workflow_run:
    workflows:
      - 'Lint on Push'
      - 'Run Unit Tests on push / pull'
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Staging server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -tt <<EOF
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin main
            # Add any other deployment commands here
            exit
          EOF
