- name: Deploy to Staging server
  uses: easingthemes/ssh-deploy@main
  with:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    REMOTE_USER: ${{ secrets.REMOTE_USER }}
    TARGET: ${{ secrets.REMOTE_TARGET }}
    SCRIPT_BEFORE: |
      whoami
      ls -al
    SCRIPT_AFTER: |
      ssh -i SSH_PRIVATE_KEY REMOTE_USER@ec2-13-40-119-155.eu-west-2.compute.amazonaws.com
