name: Push Pull Commit

on:
  push:
    branches:
      - main

jobs:
  echo_message:
    runs-on: ubuntu-latest # Machine to run on
    steps:
      - run: node --version # Use whatever the node version is of the agent running the script
      - run: npm --version # Use whatever the npm version is of the agent running
      - run: echo "Push successful"
